# Generated by Django 4.1.7 on 2023-03-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('issue_type', models.CharField(choices=[('Printer', 'PRINTER'), ('Network', 'NETWORK'), ('Computer', 'COMPUTER'), ('Software', 'SOFTWARE'), ('Email', 'EMAIL'), ('Other', 'OTHER')], default='Printer', max_length=15)),
                ('status', models.CharField(choices=[('Unassigned', 'UNASSIGNED'), ('Assigned', 'ASSIGNED'), ('Rejected', 'REJECTED'), ('Completed', 'COMPLETED')], default='Unassigned', max_length=15)),
                ('ticket_no', models.CharField(max_length=50)),
                ('emp_email', models.EmailField(max_length=254, null=True, verbose_name='email address')),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_phone', models.CharField(max_length=10)),
                ('emp_designation', models.CharField(max_length=100)),
                ('emp_organization', models.CharField(choices=[('NSL', 'SNL'), ('Mecon', 'MECON'), ('Other', 'Other')], default='NSL', max_length=15)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=259)),
                ('assign_name', models.CharField(max_length=50, null=True)),
                ('assign_phone', models.CharField(max_length=10, null=True)),
                ('issue_date', models.DateTimeField()),
                ('resolved_date', models.DateTimeField(null=True)),
                ('rejected_date', models.DateTimeField(null=True)),
                ('rejected_reason', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
