# Generated by Django 4.1.7 on 2023-03-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues',
            name='assigned_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='issues',
            name='emp_designation',
            field=models.CharField(choices=[('Tco', 'TCO'), ('Field Attendant', 'FIELD ATTENDANT'), ('Junior Assistant', 'JUNIOR ASSISTANT'), ('Junior Officer', 'JUNIOR OFFICER'), ('Junior Manager', 'JUNIOR MANAGER'), ('Executive Trainee', 'EXECUTIVE TRAINEE'), ('Assistant Manager', 'ASSISTANT MANAGER'), ('Deputy Manager', 'DEPUTY MANAGER'), ('Manager', 'MANAGER'), ('Senior Manager', 'SENIOR MANAGER'), ('Agm', 'AGM'), ('Dgm', 'DGM'), ('Gm', 'GM'), ('Cgm', 'CGM'), ('Ed', 'ED')], default='Tco', max_length=20),
        ),
        migrations.AlterField(
            model_name='issues',
            name='emp_organization',
            field=models.CharField(choices=[('Nsl', 'NSL'), ('Mecon', 'MECON'), ('Other', 'OTHER')], default='Nsl', max_length=15),
        ),
        migrations.AlterField(
            model_name='issues',
            name='location',
            field=models.CharField(choices=[('Rmhs_Aso Building', 'RMHS_ASO BUILDING'), ('Coke Oven_Cdcp Boiler_By Product_Aso Building', 'COKE OVEN_CDCP BOILER_BY PRODUCT_ASO BUILDING'), ('Sinter Plant_Aso Building', 'SINTER PLANT_ASO BUILDING'), ('Power & Blowing Station (Pbs)_Blast Furnace Aso Building', 'POWER & BLOWING STATION (PBS)_BLAST FURNACE ASO BUILDING'), ('Sms_Oxygen_Aso Building', 'SMS_OXYGEN_ASO BUILDING'), ('Thin Slab Caster & Hot Strip Mill(Tsc&Hsm)_Central R&Cl-Aso Building', 'THIN SLAB CASTER & HOT STRIP MILL(TSC&HSM)_CENTRAL R&CL-ASO BUILDING'), ('Cmos_Aso Building', 'CMOS_ASO BUILDING'), ('Old Project Office A-Block', 'OLD PROJECT OFFICE A-BLOCK'), ('Old Project Office B-Block', 'OLD PROJECT OFFICE B-BLOCK'), ('Old Project Office C-Block', 'OLD PROJECT OFFICE -C-BLOCK'), ('D-Block', 'D-BLOCK'), ('E-Block', 'E-BLOCK'), ('Mrss', 'MRSS'), ('Fire Station', 'FIRE STATION'), ('Telecom', 'TELECOM'), ('Sinter Plant Admin Building (Pkg-04)', 'SINTER PLANT ADMIN BUILDING (PKG-04)'), ('Blast Furnace Admin Building (Pkg-05)', 'BLAST FURNACE ADMIN BUILDING (PKG-05)'), ('Ldcp Admin Building (Pkg-08)', 'LDCP ADMIN BUILDING (PKG-08)'), ('Sms Admin Building (Pkg-06)', 'SMS ADMIN BUILDING (PKG-06)'), ('Tsc&Hsm Admin Building (Pkg-07)', 'TSC&HSM ADMIN BUILDING (PKG-07)'), ('Oxygen Plant Admin Building (Pkg-09)', 'OXYGEN PLANT ADMIN BUILDING (PKG-09)'), ('Coke Oven Admin Building (Pkg-02)', 'COKE OVEN ADMIN BUILDING (PKG-02)'), ('By Product Admin Building (Pkg-03)', 'BY PRODUCT ADMIN BUILDING (PKG-03)'), ('Rmhs Admin Building (Pkg-01)', 'RMHS ADMIN BUILDING (PKG-01)'), ('Pbs Admin Building (Pkg-10)', 'PBS ADMIN BUILDING (PKG-10)')], default='Rmhs_Aso Building', max_length=80),
        ),
    ]
